import { useSyncExternalStore } from 'react';

export type Lang = 'id' | 'en' | 'ms' | 'ar';
export const LANGUAGES: { key: Lang; label: string; native: string; locale: string; flag: string }[] = [
  { key: 'id', label: 'Indonesia', native: 'Bahasa Indonesia', locale: 'id-ID', flag: 'ID' },
  { key: 'en', label: 'English', native: 'English', locale: 'en-US', flag: 'EN' },
  { key: 'ms', label: 'Melayu', native: 'Bahasa Melayu', locale: 'ms-MY', flag: 'MY' },
  { key: 'ar', label: 'Arabic', native: 'العربية', locale: 'ar-SA', flag: 'AR' },
];

const id = {
  // tabs & common
  'tab.home': 'Beranda', 'tab.qibla': 'Kiblat', 'tab.focus': 'Blocker', 'tab.quran': 'Al-Qur’an', 'tab.progress': 'Progres',
  'common.settings': 'Pengaturan', 'common.close': 'Tutup', 'common.save': 'Simpan', 'common.cancel': 'Batal', 'common.ok': 'Mengerti', 'common.days': 'hari', 'common.pro': 'PRO', 'common.soon': 'Segera hadir', 'common.active': 'Aktif', 'common.inactive': 'Nonaktif', 'common.minutes': 'menit', 'common.tryAgain': 'Coba lagi', 'common.retry': 'Jadwal belum tersedia. Ketuk untuk mencoba lagi.',
  'prayer.Subuh': 'Subuh', 'prayer.Zuhur': 'Zuhur', 'prayer.Asar': 'Asar', 'prayer.Magrib': 'Magrib', 'prayer.Isya': 'Isya',
  // home
  'home.morning': 'Selamat pagi', 'home.noon': 'Selamat siang', 'home.afternoon': 'Selamat sore', 'home.night': 'Selamat malam', 'home.friend': 'Sahabat', 'home.brother': 'Akhi', 'home.sister': 'Ukhti',
  'home.salam': 'Assalamu’alaikum', 'home.nextPrayer': 'SALAT BERIKUTNYA', 'home.tomorrow': 'BESOK', 'home.today': 'Salat hari ini', 'home.doneOf': '{n} dari 5 selesai', 'home.byLocation': 'Jadwal salat berdasarkan lokasi',
  'home.blockerOn': 'BLOKIR AKTIF', 'home.blockerOff': 'BLOKIR NONAKTIF', 'home.pauseApps': 'Jeda aplikasi saat azan', 'home.beforeAdhan': '{n} menit sebelum azan · {apps} aplikasi', 'home.tapEnable': 'Ketuk untuk mengaktifkan pemblokir',
  'home.nextAlarm': 'ALARM BERIKUTNYA', 'home.dzikirAlarm': 'ALARM DZIKIR', 'home.wakeDzikir': 'Bangun dengan dzikir', 'home.alarmHint': 'Atur tanggal & jam, alarm berbunyi di HP-mu', 'home.in': 'dalam',
  'home.qibla': 'Kiblat', 'home.kaaba': 'Arah Ka’bah', 'home.quran': 'Al-Qur’an', 'home.surahs': '114 surah', 'home.sunnah': 'Salat sunah', 'home.sunnahSub': 'Pengingat & niat',
  'home.proTitle': 'Pengingat salat sunah, mode malam,\nsuara premium & widget', 'home.proActive': 'Pratinjau aktif · Jelajahi', 'home.proTry': 'Coba pratinjau gratis', 'home.verse': 'Seayat untuk hari ini', 'home.read': 'Baca',
  'home.eventToday': 'HARI INI', 'home.eventIn': '{n} HARI LAGI', 'home.source': 'Cocokkan dengan masjid setempat.', 'home.initialLocation': '(lokasi awal)',
  // settings
  'settings.title': 'Pengaturan', 'settings.subtitle': 'Azam, sesuai kenyamananmu.', 'settings.guest': 'Menjelajah tanpa akun', 'settings.changePhoto': 'Ganti foto', 'settings.addPhoto': 'Tambah foto', 'settings.removePhoto': 'Hapus foto', 'settings.photoSaved': 'Foto profil diperbarui.', 'settings.photoRemoved': 'Foto profil dihapus.', 'settings.photoPermission': 'Izin galeri diperlukan untuk memilih foto.', 'settings.openSettings': 'Buka Pengaturan izin', 'settings.editName': 'Ubah nama',
  'settings.worship': 'Preferensi ibadah', 'settings.location': 'Lokasi & jadwal salat', 'settings.notifications': 'Notifikasi salat', 'settings.notifOn': 'Izin diaktifkan', 'settings.notifOff': 'Ketuk untuk mengatur izin', 'settings.adhan': 'Suara azan', 'settings.adhanOn': 'Azan berkumandang saat waktu salat tiba', 'settings.adhanOff': 'Hanya pengingat tanpa suara azan',
  'settings.sunnah': 'Pengingat salat sunah', 'settings.sunnahValue': '{n} aktif · Tahajud, Dhuha, Witir, Rawatib', 'settings.blockBefore': 'Blokir sebelum azan', 'settings.blockValue': '{n} menit · atur di App Blocker', 'settings.alarm': 'Alarm dzikir', 'settings.alarmValue': '{n} alarm aktif · tanggal, jam & pengulangan', 'settings.gender': 'Jenis kelamin', 'settings.male': 'Laki-laki', 'settings.female': 'Perempuan', 'settings.unset': 'Belum diatur',
  'settings.display': 'Tampilan & kenyamanan', 'settings.language': 'Bahasa / Language', 'settings.dark': 'Mode malam', 'settings.darkSub': 'Biru lebih pekat · pratinjau Pro', 'settings.ambient': 'Suasana tenang', 'settings.ambientValue': 'Hujan {r}% · Kucing {c}% · ramah ADHD', 'settings.widget': 'Widget & ikon', 'settings.widgetSub': 'Pratinjau desain Pro', 'settings.ads': 'Tentang iklan', 'settings.adsSub': 'Belum ada iklan pada versi ini',
  'settings.about': 'Tentang Azam', 'settings.guide': 'Lihat lagi cara penggunaan', 'settings.privacy': 'Privasi & sumber data', 'settings.version': 'Azam – App Blocker', 'settings.versionSub': 'Versi 2.1 · Dengan niat baik', 'settings.logout': 'Keluar dari sesi', 'settings.footer': 'Dibuat untuk jeda yang lebih bermakna.',
  'settings.proBanner': 'Pengingat salat sunah,\nmode malam & suara premium.', 'settings.proLink': 'Jelajahi pratinjau Pro →',
  'language.title': 'Pilih bahasa', 'language.hint': 'Antarmuka utama mengikuti bahasa ini. Ayat Al-Qur’an tetap dalam bahasa Arab dengan terjemahan Indonesia.',
  // pro
  'pro.title': 'Azam Pro', 'pro.subtitle': 'Ruang yang lebih personal untuk iman.', 'pro.heroBadge': 'AZAM PRO', 'pro.heroBadgeActive': 'PRATINJAU PRO AKTIF', 'pro.heroTitle': 'Sedikit jeda.\nLebih banyak makna.', 'pro.heroText': 'Semua ibadah utama tetap gratis. Pro menambah kedalaman: pengingat sunah, mode malam, suara, widget.',
  'pro.monthly': 'Bulanan', 'pro.monthlySub': 'Fleksibel, berhenti kapan saja', 'pro.yearly': 'Tahunan', 'pro.yearlySub': 'Paling hemat · 2 bulan gratis', 'pro.best': 'TERBAIK', 'pro.soonPrice': 'Segera', 'pro.previewOn': 'Pratinjau Pro aktif ✓', 'pro.previewTry': 'Coba pratinjau Pro gratis', 'pro.get': 'Yang kamu dapatkan', 'pro.compare': 'Gratis vs Pro', 'pro.feature': 'Fitur', 'pro.free': 'Gratis', 'pro.footer': 'Belum ada tagihan pada versi ini. Al-Qur’an lengkap dan terjemahan tetap gratis untuk semua.', 'pro.paymentSoon': 'Langganan Pro dibuka setelah pembayaran aktif. Nikmati pratinjau gratis dulu.',
  'pro.f.sunnah': 'Pengingat salat sunah', 'pro.f.sunnahText': 'Tahajud, Dhuha, Witir, Rawatib · niat Arab & Latin.', 'pro.f.sunnahBadge': 'Atur pengingat',
  'pro.f.dark': 'Mode malam', 'pro.f.darkText': 'Biru pekat, nyaman saat qiyamul lail.', 'pro.f.darkOn': 'Aktif ✓', 'pro.f.darkTry': 'Coba sekarang',
  'pro.f.sound': 'Suara premium', 'pro.f.verse': 'Jeda dengan ayat', 'pro.f.verseText': 'Layar jeda salat menampilkan ayat harian.', 'pro.f.demo': 'Demonstrasi',
  'pro.f.widget': 'Widget layar kunci', 'pro.f.widgetText': 'Ayat harian & hitung mundur azan.', 'pro.f.widgetBadge': 'Lihat desain',
  'pro.f.hajj': 'Haji & Umrah', 'pro.f.hajjText': 'Panduan bertahap: persiapan, umrah, haji, doa.', 'pro.f.hajjBadge': 'Buka panduan',
  'pro.f.rakaat': 'Penghitung rakaat', 'pro.f.rakaatText': 'Riset sensor · belum tersedia.', 'pro.f.concept': 'Konsep',
  'pro.c.basic': 'Jadwal salat, Al-Qur’an, kiblat, streak', 'pro.c.ambient': 'Hujan & kucing (volume)', 'pro.c.sunnah': 'Pengingat salat sunah + niat', 'pro.c.dark': 'Mode malam & widget layar kunci', 'pro.c.sound': 'Suara premium: petir, ombak, api, burung', 'pro.c.verse': 'Jeda salat dengan ayat', 'pro.c.hajj': 'Panduan Haji & Umrah', 'pro.c.ads': 'Bebas iklan selamanya',
  // sunnah
  'sunnah.title': 'Salat sunah', 'sunnah.subtitle': 'Pengingat lembut & niat yang siap dibaca.', 'sunnah.proNote': 'Fitur Pro · aktifkan pratinjau gratis untuk menyalakan pengingat.', 'sunnah.enablePro': 'Aktifkan pratinjau Pro', 'sunnah.reminder': 'Pengingat', 'sunnah.niat': 'NIAT', 'sunnah.time': 'Perkiraan waktu', 'sunnah.rakaat': 'rakaat', 'sunnah.on': 'Pengingat {name} aktif.', 'sunnah.off': 'Pengingat {name} dimatikan.', 'sunnah.notifHint': 'Pengingat dikirim lewat notifikasi HP saat Azam telah diberi izin notifikasi.', 'sunnah.needNotif': 'Izin notifikasi belum aktif · atur di Pengaturan → Notifikasi salat.', 'sunnah.footer': 'Waktu dihitung dari jadwal salat lokasimu. Ikuti pembimbing setempat untuk fikih yang lebih rinci.',
  'sunnah.tahajud': 'Tahajud', 'sunnah.tahajudDesc': 'Salat malam di sepertiga malam terakhir setelah tidur. 2–12 rakaat, ditutup witir.', 'sunnah.tahajudTime': 'Sepertiga malam terakhir',
  'sunnah.dhuha': 'Dhuha', 'sunnah.dhuhaDesc': 'Salat pagi setelah matahari naik hingga sebelum Zuhur. 2–12 rakaat, pembuka rezeki.', 'sunnah.dhuhaTime': 'Setelah terbit matahari',
  'sunnah.witir': 'Witir', 'sunnah.witirDesc': 'Penutup salat malam dengan rakaat ganjil (1, 3, 5…). Setelah Isya hingga sebelum Subuh.', 'sunnah.witirTime': 'Setelah Isya',
  'sunnah.rawatib': 'Rawatib', 'sunnah.rawatibDesc': 'Sunah pengiring salat fardu: 2 sebelum Subuh, 2–4 sebelum & 2 sesudah Zuhur, 2 sesudah Magrib, 2 sesudah Isya.', 'sunnah.rawatibTime': 'Sebelum & sesudah salat fardu',
  'sunnah.meaning.tahajud': 'Aku niat salat sunah tahajud dua rakaat karena Allah Ta’ala.', 'sunnah.meaning.dhuha': 'Aku niat salat sunah dhuha dua rakaat karena Allah Ta’ala.', 'sunnah.meaning.witir': 'Aku niat salat sunah witir satu rakaat karena Allah Ta’ala.', 'sunnah.meaning.rawatib': 'Aku niat salat sunah qabliyah Subuh dua rakaat karena Allah Ta’ala.',
  // focus / blocker
  'focus.title': 'App Blocker', 'focus.subtitle': 'Dunia bisa menunggu. Salat dulu.', 'focus.demo': 'DEMONSTRASI DALAM APLIKASI', 'focus.blocking': 'Pemblokiran aplikasi', 'focus.onSub': 'Aktif · {n} menit sebelum azan', 'focus.offSub': 'Nonaktif · geser untuk mengaktifkan',
  // share
  'share.ownPhoto': 'Foto sendiri', 'share.removePhoto': 'Hapus foto', 'share.selfie': 'Selfie', 'share.gallery': 'Galeri', 'share.center': 'Di tengah', 'share.full': 'Layar penuh', 'share.template': 'Latar template', 'share.tone': 'Nuansa', 'share.caption': 'Caption', 'share.shuffle': 'Acak', 'share.stats': 'Statistik', 'share.name': 'Nama & kota', 'share.verse': 'Ayat', 'share.buttonWeb': 'Bagikan sebagai teks', 'share.button': 'Bagikan ke Story / WhatsApp', 'share.photoHintWeb': 'Selfie kamera tersedia di ponsel; di web pilih dari galeri.', 'share.photoHint': 'Fotomu bisa memenuhi seluruh kartu (layar penuh) atau berada di tengah.',
  // modal titles
  'modal.location': 'Atur lokasi', 'modal.notifications': 'Pengingat salat', 'modal.alarm-form': 'Alarm baru', 'modal.success': 'Satu langkah baik', 'modal.share-verse': 'Bagikan ayat', 'modal.share-progress': 'Bagikan ke Story', 'modal.share-badge': 'Bagikan lencana', 'modal.day': 'Catatan salat', 'modal.ambient': 'Suasana tenang', 'modal.adhan': 'Waktu salat', 'modal.add-app': 'Tambah aplikasi', 'modal.widget-preview': 'Ayat di layar kunci', 'modal.rakaat-preview': 'Penghitung rakaat', 'modal.logout': 'Keluar dari Azam?', 'modal.language': 'Bahasa / Language', 'modal.profile': 'Profil',
};
type Keys = keyof typeof id;

const en: Record<Keys, string> = {
  'tab.home': 'Home', 'tab.qibla': 'Qibla', 'tab.focus': 'Blocker', 'tab.quran': 'Qur’an', 'tab.progress': 'Progress',
  'common.settings': 'Settings', 'common.close': 'Close', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.ok': 'Got it', 'common.days': 'days', 'common.pro': 'PRO', 'common.soon': 'Coming soon', 'common.active': 'On', 'common.inactive': 'Off', 'common.minutes': 'min', 'common.tryAgain': 'Try again', 'common.retry': 'Schedule unavailable. Tap to retry.',
  'prayer.Subuh': 'Fajr', 'prayer.Zuhur': 'Dhuhr', 'prayer.Asar': 'Asr', 'prayer.Magrib': 'Maghrib', 'prayer.Isya': 'Isha',
  'home.morning': 'Good morning', 'home.noon': 'Good afternoon', 'home.afternoon': 'Good afternoon', 'home.night': 'Good evening', 'home.friend': 'Friend', 'home.brother': 'Brother', 'home.sister': 'Sister',
  'home.salam': 'Assalamu’alaikum', 'home.nextPrayer': 'NEXT PRAYER', 'home.tomorrow': 'TOMORROW', 'home.today': 'Today’s prayers', 'home.doneOf': '{n} of 5 done', 'home.byLocation': 'Prayer times based on your location',
  'home.blockerOn': 'BLOCKER ON', 'home.blockerOff': 'BLOCKER OFF', 'home.pauseApps': 'Pause apps at adhan', 'home.beforeAdhan': '{n} min before adhan · {apps} apps', 'home.tapEnable': 'Tap to enable the blocker',
  'home.nextAlarm': 'NEXT ALARM', 'home.dzikirAlarm': 'DHIKR ALARM', 'home.wakeDzikir': 'Wake up with dhikr', 'home.alarmHint': 'Set date & time, the alarm rings on your phone', 'home.in': 'in',
  'home.qibla': 'Qibla', 'home.kaaba': 'Kaaba direction', 'home.quran': 'Qur’an', 'home.surahs': '114 surahs', 'home.sunnah': 'Sunnah prayers', 'home.sunnahSub': 'Reminders & intention',
  'home.proTitle': 'Sunnah reminders, night mode,\npremium sounds & widgets', 'home.proActive': 'Preview active · Explore', 'home.proTry': 'Try the free preview', 'home.verse': 'A verse for today', 'home.read': 'Read',
  'home.eventToday': 'TODAY', 'home.eventIn': '{n} DAYS LEFT', 'home.source': 'Confirm with your local mosque.', 'home.initialLocation': '(default location)',
  'settings.title': 'Settings', 'settings.subtitle': 'Azam, the way you like it.', 'settings.guest': 'Browsing as guest', 'settings.changePhoto': 'Change photo', 'settings.addPhoto': 'Add photo', 'settings.removePhoto': 'Remove photo', 'settings.photoSaved': 'Profile photo updated.', 'settings.photoRemoved': 'Profile photo removed.', 'settings.photoPermission': 'Photo library permission is needed to pick a photo.', 'settings.openSettings': 'Open permission settings', 'settings.editName': 'Edit name',
  'settings.worship': 'Worship preferences', 'settings.location': 'Location & prayer times', 'settings.notifications': 'Prayer notifications', 'settings.notifOn': 'Permission granted', 'settings.notifOff': 'Tap to set permission', 'settings.adhan': 'Adhan sound', 'settings.adhanOn': 'Adhan plays when prayer time arrives', 'settings.adhanOff': 'Reminder only, no adhan sound',
  'settings.sunnah': 'Sunnah prayer reminders', 'settings.sunnahValue': '{n} active · Tahajjud, Duha, Witr, Rawatib', 'settings.blockBefore': 'Block before adhan', 'settings.blockValue': '{n} min · set in App Blocker', 'settings.alarm': 'Dhikr alarm', 'settings.alarmValue': '{n} active alarms · date, time & repeat', 'settings.gender': 'Gender', 'settings.male': 'Male', 'settings.female': 'Female', 'settings.unset': 'Not set',
  'settings.display': 'Display & comfort', 'settings.language': 'Language', 'settings.dark': 'Night mode', 'settings.darkSub': 'Deeper blue · Pro preview', 'settings.ambient': 'Calm ambience', 'settings.ambientValue': 'Rain {r}% · Cat {c}% · ADHD friendly', 'settings.widget': 'Widgets & icons', 'settings.widgetSub': 'Pro design preview', 'settings.ads': 'About ads', 'settings.adsSub': 'No ads in this version',
  'settings.about': 'About Azam', 'settings.guide': 'Watch the guide again', 'settings.privacy': 'Privacy & data sources', 'settings.version': 'Azam – App Blocker', 'settings.versionSub': 'Version 2.1 · With good intention', 'settings.logout': 'Sign out', 'settings.footer': 'Made for a more meaningful pause.',
  'settings.proBanner': 'Sunnah reminders,\nnight mode & premium sounds.', 'settings.proLink': 'Explore the Pro preview →',
  'language.title': 'Choose language', 'language.hint': 'The main interface follows this language. Qur’an verses stay in Arabic with Indonesian translation.',
  'pro.title': 'Azam Pro', 'pro.subtitle': 'A more personal space for faith.', 'pro.heroBadge': 'AZAM PRO', 'pro.heroBadgeActive': 'PRO PREVIEW ACTIVE', 'pro.heroTitle': 'A little pause.\nA lot more meaning.', 'pro.heroText': 'All core worship stays free. Pro adds depth: sunnah reminders, night mode, sounds, widgets.',
  'pro.monthly': 'Monthly', 'pro.monthlySub': 'Flexible, cancel anytime', 'pro.yearly': 'Yearly', 'pro.yearlySub': 'Best value · 2 months free', 'pro.best': 'BEST', 'pro.soonPrice': 'Soon', 'pro.previewOn': 'Pro preview active ✓', 'pro.previewTry': 'Try the free Pro preview', 'pro.get': 'What you get', 'pro.compare': 'Free vs Pro', 'pro.feature': 'Feature', 'pro.free': 'Free', 'pro.footer': 'No charges in this version. The full Qur’an and translation stay free for everyone.', 'pro.paymentSoon': 'Pro subscription opens once payments are live. Enjoy the free preview for now.',
  'pro.f.sunnah': 'Sunnah prayer reminders', 'pro.f.sunnahText': 'Tahajjud, Duha, Witr, Rawatib · intention in Arabic & Latin.', 'pro.f.sunnahBadge': 'Set reminders',
  'pro.f.dark': 'Night mode', 'pro.f.darkText': 'Deep blue, gentle for night prayers.', 'pro.f.darkOn': 'Active ✓', 'pro.f.darkTry': 'Try it now',
  'pro.f.sound': 'Premium sounds', 'pro.f.verse': 'Pause with a verse', 'pro.f.verseText': 'The prayer pause screen shows the daily verse.', 'pro.f.demo': 'Demo',
  'pro.f.widget': 'Lock-screen widget', 'pro.f.widgetText': 'Daily verse & adhan countdown.', 'pro.f.widgetBadge': 'See design',
  'pro.f.hajj': 'Hajj & Umrah', 'pro.f.hajjText': 'Step-by-step guide: preparation, umrah, hajj, duas.', 'pro.f.hajjBadge': 'Open guide',
  'pro.f.rakaat': 'Rak’ah counter', 'pro.f.rakaatText': 'Sensor research · not available yet.', 'pro.f.concept': 'Concept',
  'pro.c.basic': 'Prayer times, Qur’an, qibla, streaks', 'pro.c.ambient': 'Rain & cat (volume)', 'pro.c.sunnah': 'Sunnah reminders + intentions', 'pro.c.dark': 'Night mode & lock-screen widget', 'pro.c.sound': 'Premium sounds: thunder, waves, fire, birds', 'pro.c.verse': 'Prayer pause with a verse', 'pro.c.hajj': 'Hajj & Umrah guide', 'pro.c.ads': 'Ad-free forever',
  'sunnah.title': 'Sunnah prayers', 'sunnah.subtitle': 'Gentle reminders & ready-to-read intentions.', 'sunnah.proNote': 'Pro feature · turn on the free preview to enable reminders.', 'sunnah.enablePro': 'Enable Pro preview', 'sunnah.reminder': 'Reminder', 'sunnah.niat': 'INTENTION', 'sunnah.time': 'Estimated time', 'sunnah.rakaat': 'rak’ahs', 'sunnah.on': '{name} reminder on.', 'sunnah.off': '{name} reminder off.', 'sunnah.notifHint': 'Reminders arrive as phone notifications once Azam has notification permission.', 'sunnah.needNotif': 'Notification permission is off · set it in Settings → Prayer notifications.', 'sunnah.footer': 'Times are derived from your local prayer schedule. Follow your local teacher for detailed rulings.',
  'sunnah.tahajud': 'Tahajjud', 'sunnah.tahajudDesc': 'Night prayer in the last third of the night after sleeping. 2–12 rak’ahs, closed with Witr.', 'sunnah.tahajudTime': 'Last third of the night',
  'sunnah.dhuha': 'Duha', 'sunnah.dhuhaDesc': 'Morning prayer after sunrise until before Dhuhr. 2–12 rak’ahs, an opener of provision.', 'sunnah.dhuhaTime': 'After sunrise',
  'sunnah.witir': 'Witr', 'sunnah.witirDesc': 'Closes the night prayers with an odd number of rak’ahs (1, 3, 5…). After Isha until before Fajr.', 'sunnah.witirTime': 'After Isha',
  'sunnah.rawatib': 'Rawatib', 'sunnah.rawatibDesc': 'Sunnah around the obligatory prayers: 2 before Fajr, 2–4 before & 2 after Dhuhr, 2 after Maghrib, 2 after Isha.', 'sunnah.rawatibTime': 'Before & after obligatory prayers',
  'sunnah.meaning.tahajud': 'I intend to pray two rak’ahs of sunnah Tahajjud for Allah the Exalted.', 'sunnah.meaning.dhuha': 'I intend to pray two rak’ahs of sunnah Duha for Allah the Exalted.', 'sunnah.meaning.witir': 'I intend to pray one rak’ah of sunnah Witr for Allah the Exalted.', 'sunnah.meaning.rawatib': 'I intend to pray two rak’ahs of sunnah before Fajr for Allah the Exalted.',
  'focus.title': 'App Blocker', 'focus.subtitle': 'The world can wait. Prayer first.', 'focus.demo': 'IN-APP DEMONSTRATION', 'focus.blocking': 'App blocking', 'focus.onSub': 'On · {n} min before adhan', 'focus.offSub': 'Off · toggle to enable',
  'share.ownPhoto': 'Your photo', 'share.removePhoto': 'Remove photo', 'share.selfie': 'Selfie', 'share.gallery': 'Gallery', 'share.center': 'Centered', 'share.full': 'Full screen', 'share.template': 'Template background', 'share.tone': 'Tone', 'share.caption': 'Caption', 'share.shuffle': 'Shuffle', 'share.stats': 'Stats', 'share.name': 'Name & city', 'share.verse': 'Verse', 'share.buttonWeb': 'Share as text', 'share.button': 'Share to Story / WhatsApp', 'share.photoHintWeb': 'Camera selfie is available on phones; on web pick from the gallery.', 'share.photoHint': 'Your photo can fill the whole card (full screen) or sit in the centre.',
  'modal.location': 'Set location', 'modal.notifications': 'Prayer reminders', 'modal.alarm-form': 'New alarm', 'modal.success': 'One good step', 'modal.share-verse': 'Share verse', 'modal.share-progress': 'Share to Story', 'modal.share-badge': 'Share badge', 'modal.day': 'Prayer log', 'modal.ambient': 'Calm ambience', 'modal.adhan': 'Prayer time', 'modal.add-app': 'Add app', 'modal.widget-preview': 'Verse on lock screen', 'modal.rakaat-preview': 'Rak’ah counter', 'modal.logout': 'Sign out of Azam?', 'modal.language': 'Language', 'modal.profile': 'Profile',
};

const ms: Record<Keys, string> = {
  ...en,
  'tab.home': 'Utama', 'tab.qibla': 'Kiblat', 'tab.focus': 'Penyekat', 'tab.quran': 'Al-Qur’an', 'tab.progress': 'Kemajuan',
  'common.settings': 'Tetapan', 'common.close': 'Tutup', 'common.save': 'Simpan', 'common.cancel': 'Batal', 'common.ok': 'Faham', 'common.days': 'hari', 'common.soon': 'Akan datang', 'common.active': 'Aktif', 'common.inactive': 'Tidak aktif', 'common.minutes': 'minit', 'common.tryAgain': 'Cuba lagi', 'common.retry': 'Jadual belum tersedia. Ketik untuk cuba lagi.',
  'prayer.Subuh': 'Subuh', 'prayer.Zuhur': 'Zohor', 'prayer.Asar': 'Asar', 'prayer.Magrib': 'Maghrib', 'prayer.Isya': 'Isyak',
  'home.morning': 'Selamat pagi', 'home.noon': 'Selamat tengah hari', 'home.afternoon': 'Selamat petang', 'home.night': 'Selamat malam', 'home.friend': 'Sahabat', 'home.brother': 'Akhi', 'home.sister': 'Ukhti',
  'home.nextPrayer': 'SOLAT SETERUSNYA', 'home.tomorrow': 'ESOK', 'home.today': 'Solat hari ini', 'home.doneOf': '{n} daripada 5 selesai', 'home.byLocation': 'Waktu solat berdasarkan lokasi',
  'home.blockerOn': 'SEKATAN AKTIF', 'home.blockerOff': 'SEKATAN TIDAK AKTIF', 'home.pauseApps': 'Jeda aplikasi ketika azan', 'home.beforeAdhan': '{n} minit sebelum azan · {apps} aplikasi', 'home.tapEnable': 'Ketik untuk mengaktifkan penyekat',
  'home.nextAlarm': 'PENGGERA SETERUSNYA', 'home.dzikirAlarm': 'PENGGERA ZIKIR', 'home.wakeDzikir': 'Bangun dengan zikir', 'home.alarmHint': 'Tetapkan tarikh & masa, penggera berbunyi di telefon anda', 'home.in': 'dalam',
  'home.kaaba': 'Arah Kaabah', 'home.surahs': '114 surah', 'home.sunnah': 'Solat sunat', 'home.sunnahSub': 'Peringatan & niat',
  'home.proTitle': 'Peringatan solat sunat, mod malam,\nbunyi premium & widget', 'home.proActive': 'Pratonton aktif · Teroka', 'home.proTry': 'Cuba pratonton percuma', 'home.verse': 'Seayat untuk hari ini', 'home.read': 'Baca',
  'home.eventToday': 'HARI INI', 'home.eventIn': '{n} HARI LAGI', 'home.source': 'Sahkan dengan masjid setempat.', 'home.initialLocation': '(lokasi awal)',
  'settings.title': 'Tetapan', 'settings.subtitle': 'Azam, mengikut keselesaan anda.', 'settings.guest': 'Melayari tanpa akaun', 'settings.changePhoto': 'Tukar foto', 'settings.addPhoto': 'Tambah foto', 'settings.removePhoto': 'Padam foto', 'settings.photoSaved': 'Foto profil dikemas kini.', 'settings.photoRemoved': 'Foto profil dipadam.', 'settings.photoPermission': 'Kebenaran galeri diperlukan untuk memilih foto.', 'settings.openSettings': 'Buka tetapan kebenaran', 'settings.editName': 'Ubah nama',
  'settings.worship': 'Keutamaan ibadah', 'settings.location': 'Lokasi & waktu solat', 'settings.notifications': 'Notifikasi solat', 'settings.notifOn': 'Kebenaran diberikan', 'settings.notifOff': 'Ketik untuk menetapkan kebenaran', 'settings.adhan': 'Bunyi azan', 'settings.adhanOn': 'Azan berkumandang apabila masuk waktu', 'settings.adhanOff': 'Peringatan sahaja tanpa azan',
  'settings.sunnah': 'Peringatan solat sunat', 'settings.sunnahValue': '{n} aktif · Tahajud, Dhuha, Witir, Rawatib', 'settings.blockBefore': 'Sekat sebelum azan', 'settings.blockValue': '{n} minit · tetapkan di App Blocker', 'settings.alarm': 'Penggera zikir', 'settings.alarmValue': '{n} penggera aktif · tarikh, masa & ulangan', 'settings.gender': 'Jantina', 'settings.male': 'Lelaki', 'settings.female': 'Perempuan', 'settings.unset': 'Belum ditetapkan',
  'settings.display': 'Paparan & keselesaan', 'settings.language': 'Bahasa / Language', 'settings.dark': 'Mod malam', 'settings.darkSub': 'Biru lebih pekat · pratonton Pro', 'settings.ambient': 'Suasana tenang', 'settings.ambientValue': 'Hujan {r}% · Kucing {c}% · mesra ADHD', 'settings.widget': 'Widget & ikon', 'settings.widgetSub': 'Pratonton reka bentuk Pro', 'settings.ads': 'Tentang iklan', 'settings.adsSub': 'Tiada iklan pada versi ini',
  'settings.about': 'Tentang Azam', 'settings.guide': 'Lihat semula panduan', 'settings.privacy': 'Privasi & sumber data', 'settings.versionSub': 'Versi 2.1 · Dengan niat baik', 'settings.logout': 'Log keluar', 'settings.footer': 'Dibina untuk jeda yang lebih bermakna.',
  'settings.proBanner': 'Peringatan solat sunat,\nmod malam & bunyi premium.', 'settings.proLink': 'Teroka pratonton Pro →',
  'language.title': 'Pilih bahasa', 'language.hint': 'Antara muka utama mengikut bahasa ini. Ayat Al-Qur’an kekal dalam bahasa Arab dengan terjemahan Indonesia.',
  'pro.subtitle': 'Ruang lebih peribadi untuk iman.', 'pro.heroBadgeActive': 'PRATONTON PRO AKTIF', 'pro.heroTitle': 'Sedikit jeda.\nLebih banyak makna.', 'pro.heroText': 'Semua ibadah utama kekal percuma. Pro menambah kedalaman: peringatan sunat, mod malam, bunyi, widget.',
  'pro.monthly': 'Bulanan', 'pro.monthlySub': 'Fleksibel, berhenti bila-bila masa', 'pro.yearly': 'Tahunan', 'pro.yearlySub': 'Paling jimat · 2 bulan percuma', 'pro.best': 'TERBAIK', 'pro.soonPrice': 'Akan datang', 'pro.previewOn': 'Pratonton Pro aktif ✓', 'pro.previewTry': 'Cuba pratonton Pro percuma', 'pro.get': 'Apa yang anda dapat', 'pro.compare': 'Percuma vs Pro', 'pro.feature': 'Ciri', 'pro.free': 'Percuma', 'pro.footer': 'Tiada caj pada versi ini. Al-Qur’an penuh dan terjemahan kekal percuma untuk semua.', 'pro.paymentSoon': 'Langganan Pro dibuka selepas pembayaran aktif. Nikmati pratonton percuma dahulu.',
  'pro.f.sunnah': 'Peringatan solat sunat', 'pro.f.sunnahText': 'Tahajud, Dhuha, Witir, Rawatib · niat Arab & Rumi.', 'pro.f.sunnahBadge': 'Tetapkan peringatan',
  'pro.f.dark': 'Mod malam', 'pro.f.darkText': 'Biru pekat, selesa ketika qiyamullail.', 'pro.f.darkOn': 'Aktif ✓', 'pro.f.darkTry': 'Cuba sekarang',
  'pro.f.sound': 'Bunyi premium', 'pro.f.verse': 'Jeda dengan ayat', 'pro.f.verseText': 'Skrin jeda solat memaparkan ayat harian.', 'pro.f.demo': 'Demonstrasi',
  'pro.f.widget': 'Widget skrin kunci', 'pro.f.widgetText': 'Ayat harian & kiraan detik azan.', 'pro.f.widgetBadge': 'Lihat reka bentuk',
  'pro.f.hajj': 'Haji & Umrah', 'pro.f.hajjText': 'Panduan berperingkat: persiapan, umrah, haji, doa.', 'pro.f.hajjBadge': 'Buka panduan',
  'pro.f.rakaat': 'Pengira rakaat', 'pro.f.rakaatText': 'Kajian sensor · belum tersedia.', 'pro.f.concept': 'Konsep',
  'pro.c.basic': 'Waktu solat, Al-Qur’an, kiblat, streak', 'pro.c.ambient': 'Hujan & kucing (kelantangan)', 'pro.c.sunnah': 'Peringatan solat sunat + niat', 'pro.c.dark': 'Mod malam & widget skrin kunci', 'pro.c.sound': 'Bunyi premium: guruh, ombak, api, burung', 'pro.c.verse': 'Jeda solat dengan ayat', 'pro.c.hajj': 'Panduan Haji & Umrah', 'pro.c.ads': 'Bebas iklan selamanya',
  'sunnah.title': 'Solat sunat', 'sunnah.subtitle': 'Peringatan lembut & niat yang sedia dibaca.', 'sunnah.proNote': 'Ciri Pro · hidupkan pratonton percuma untuk mengaktifkan peringatan.', 'sunnah.enablePro': 'Aktifkan pratonton Pro', 'sunnah.reminder': 'Peringatan', 'sunnah.niat': 'NIAT', 'sunnah.time': 'Anggaran waktu', 'sunnah.rakaat': 'rakaat', 'sunnah.on': 'Peringatan {name} aktif.', 'sunnah.off': 'Peringatan {name} dimatikan.', 'sunnah.notifHint': 'Peringatan dihantar melalui notifikasi telefon setelah Azam diberi kebenaran notifikasi.', 'sunnah.needNotif': 'Kebenaran notifikasi belum aktif · tetapkan di Tetapan → Notifikasi solat.', 'sunnah.footer': 'Waktu dikira daripada jadual solat lokasi anda. Ikuti guru setempat untuk hukum yang lebih terperinci.',
  'sunnah.tahajud': 'Tahajud', 'sunnah.tahajudDesc': 'Solat malam pada sepertiga malam terakhir selepas tidur. 2–12 rakaat, ditutup dengan witir.', 'sunnah.tahajudTime': 'Sepertiga malam terakhir',
  'sunnah.dhuha': 'Dhuha', 'sunnah.dhuhaDesc': 'Solat pagi selepas matahari naik hingga sebelum Zohor. 2–12 rakaat, pembuka rezeki.', 'sunnah.dhuhaTime': 'Selepas matahari terbit',
  'sunnah.witir': 'Witir', 'sunnah.witirDesc': 'Penutup solat malam dengan rakaat ganjil (1, 3, 5…). Selepas Isyak hingga sebelum Subuh.', 'sunnah.witirTime': 'Selepas Isyak',
  'sunnah.rawatib': 'Rawatib', 'sunnah.rawatibDesc': 'Sunat pengiring solat fardu: 2 sebelum Subuh, 2–4 sebelum & 2 selepas Zohor, 2 selepas Maghrib, 2 selepas Isyak.', 'sunnah.rawatibTime': 'Sebelum & selepas solat fardu',
  'sunnah.meaning.tahajud': 'Sahaja aku solat sunat tahajud dua rakaat kerana Allah Ta’ala.', 'sunnah.meaning.dhuha': 'Sahaja aku solat sunat dhuha dua rakaat kerana Allah Ta’ala.', 'sunnah.meaning.witir': 'Sahaja aku solat sunat witir satu rakaat kerana Allah Ta’ala.', 'sunnah.meaning.rawatib': 'Sahaja aku solat sunat qabliyah Subuh dua rakaat kerana Allah Ta’ala.',
  'focus.subtitle': 'Dunia boleh menunggu. Solat dahulu.', 'focus.demo': 'DEMONSTRASI DALAM APLIKASI', 'focus.blocking': 'Sekatan aplikasi', 'focus.onSub': 'Aktif · {n} minit sebelum azan', 'focus.offSub': 'Tidak aktif · togol untuk mengaktifkan',
  'share.ownPhoto': 'Foto sendiri', 'share.removePhoto': 'Padam foto', 'share.selfie': 'Swafoto', 'share.gallery': 'Galeri', 'share.center': 'Di tengah', 'share.full': 'Skrin penuh', 'share.template': 'Latar templat', 'share.tone': 'Nuansa', 'share.caption': 'Kapsyen', 'share.shuffle': 'Rawak', 'share.stats': 'Statistik', 'share.name': 'Nama & bandar', 'share.verse': 'Ayat', 'share.buttonWeb': 'Kongsi sebagai teks', 'share.button': 'Kongsi ke Story / WhatsApp', 'share.photoHintWeb': 'Swafoto kamera tersedia di telefon; di web pilih daripada galeri.', 'share.photoHint': 'Foto anda boleh memenuhi seluruh kad (skrin penuh) atau berada di tengah.',
  'modal.location': 'Tetapkan lokasi', 'modal.notifications': 'Peringatan solat', 'modal.alarm-form': 'Penggera baharu', 'modal.success': 'Satu langkah baik', 'modal.share-verse': 'Kongsi ayat', 'modal.share-progress': 'Kongsi ke Story', 'modal.share-badge': 'Kongsi lencana', 'modal.day': 'Catatan solat', 'modal.ambient': 'Suasana tenang', 'modal.adhan': 'Waktu solat', 'modal.add-app': 'Tambah aplikasi', 'modal.widget-preview': 'Ayat di skrin kunci', 'modal.rakaat-preview': 'Pengira rakaat', 'modal.logout': 'Log keluar dari Azam?', 'modal.language': 'Bahasa / Language', 'modal.profile': 'Profil',
};

const ar: Record<Keys, string> = {
  ...en,
  'tab.home': 'الرئيسية', 'tab.qibla': 'القبلة', 'tab.focus': 'الحاجب', 'tab.quran': 'القرآن', 'tab.progress': 'التقدّم',
  'common.settings': 'الإعدادات', 'common.close': 'إغلاق', 'common.save': 'حفظ', 'common.cancel': 'إلغاء', 'common.ok': 'فهمت', 'common.days': 'يوم', 'common.soon': 'قريبًا', 'common.active': 'مفعّل', 'common.inactive': 'متوقف', 'common.minutes': 'دقيقة', 'common.tryAgain': 'أعد المحاولة', 'common.retry': 'الجدول غير متاح. اضغط لإعادة المحاولة.',
  'prayer.Subuh': 'الفجر', 'prayer.Zuhur': 'الظهر', 'prayer.Asar': 'العصر', 'prayer.Magrib': 'المغرب', 'prayer.Isya': 'العشاء',
  'home.morning': 'صباح الخير', 'home.noon': 'طاب يومك', 'home.afternoon': 'مساء الخير', 'home.night': 'مساء الخير', 'home.friend': 'صديقي', 'home.brother': 'أخي', 'home.sister': 'أختي',
  'home.salam': 'السلام عليكم', 'home.nextPrayer': 'الصلاة التالية', 'home.tomorrow': 'غدًا', 'home.today': 'صلوات اليوم', 'home.doneOf': '{n} من 5 مكتملة', 'home.byLocation': 'مواقيت الصلاة حسب موقعك',
  'home.blockerOn': 'الحجب مفعّل', 'home.blockerOff': 'الحجب متوقف', 'home.pauseApps': 'إيقاف التطبيقات عند الأذان', 'home.beforeAdhan': '{n} دقيقة قبل الأذان · {apps} تطبيق', 'home.tapEnable': 'اضغط لتفعيل الحاجب',
  'home.nextAlarm': 'المنبّه التالي', 'home.dzikirAlarm': 'منبّه الذكر', 'home.wakeDzikir': 'استيقظ بالذكر', 'home.alarmHint': 'حدّد التاريخ والوقت، يرنّ المنبّه على هاتفك', 'home.in': 'بعد',
  'home.qibla': 'القبلة', 'home.kaaba': 'اتجاه الكعبة', 'home.quran': 'القرآن', 'home.surahs': '114 سورة', 'home.sunnah': 'صلوات السنّة', 'home.sunnahSub': 'تذكير ونيّة',
  'home.proTitle': 'تذكير السنن، الوضع الليلي،\nأصوات مميّزة وودجات', 'home.proActive': 'المعاينة مفعّلة · استكشف', 'home.proTry': 'جرّب المعاينة مجانًا', 'home.verse': 'آية اليوم', 'home.read': 'اقرأ',
  'home.eventToday': 'اليوم', 'home.eventIn': 'بعد {n} يوم', 'home.source': 'راجع مسجدك المحلي.', 'home.initialLocation': '(الموقع الافتراضي)',
  'settings.title': 'الإعدادات', 'settings.subtitle': 'عزم، كما يريحك.', 'settings.guest': 'تصفّح كضيف', 'settings.changePhoto': 'تغيير الصورة', 'settings.addPhoto': 'إضافة صورة', 'settings.removePhoto': 'حذف الصورة', 'settings.photoSaved': 'تم تحديث صورة الملف.', 'settings.photoRemoved': 'تم حذف صورة الملف.', 'settings.photoPermission': 'يلزم إذن الوصول إلى الصور لاختيار صورة.', 'settings.openSettings': 'افتح إعدادات الأذونات', 'settings.editName': 'تعديل الاسم',
  'settings.worship': 'تفضيلات العبادة', 'settings.location': 'الموقع ومواقيت الصلاة', 'settings.notifications': 'إشعارات الصلاة', 'settings.notifOn': 'الإذن ممنوح', 'settings.notifOff': 'اضغط لضبط الإذن', 'settings.adhan': 'صوت الأذان', 'settings.adhanOn': 'يُرفع الأذان عند دخول الوقت', 'settings.adhanOff': 'تذكير فقط بدون أذان',
  'settings.sunnah': 'تذكير صلوات السنّة', 'settings.sunnahValue': '{n} مفعّل · التهجّد، الضحى، الوتر، الرواتب', 'settings.blockBefore': 'الحجب قبل الأذان', 'settings.blockValue': '{n} دقيقة · اضبطه في الحاجب', 'settings.alarm': 'منبّه الذكر', 'settings.alarmValue': '{n} منبّه مفعّل · التاريخ والوقت والتكرار', 'settings.gender': 'الجنس', 'settings.male': 'ذكر', 'settings.female': 'أنثى', 'settings.unset': 'غير محدد',
  'settings.display': 'العرض والراحة', 'settings.language': 'اللغة / Language', 'settings.dark': 'الوضع الليلي', 'settings.darkSub': 'أزرق أعمق · معاينة Pro', 'settings.ambient': 'جوّ هادئ', 'settings.ambientValue': 'مطر {r}% · قطة {c}%', 'settings.widget': 'الودجات والأيقونات', 'settings.widgetSub': 'معاينة تصميم Pro', 'settings.ads': 'حول الإعلانات', 'settings.adsSub': 'لا إعلانات في هذه النسخة',
  'settings.about': 'حول عزم', 'settings.guide': 'شاهد الدليل مجددًا', 'settings.privacy': 'الخصوصية ومصادر البيانات', 'settings.versionSub': 'الإصدار 2.1 · بنيّة صالحة', 'settings.logout': 'تسجيل الخروج', 'settings.footer': 'صُنع لوقفة أكثر معنى.',
  'settings.proBanner': 'تذكير السنن،\nالوضع الليلي وأصوات مميّزة.', 'settings.proLink': 'استكشف معاينة Pro →',
  'language.title': 'اختر اللغة', 'language.hint': 'تتبع الواجهة الرئيسية هذه اللغة. تبقى آيات القرآن بالعربية مع الترجمة الإندونيسية.',
  'pro.subtitle': 'مساحة أكثر خصوصية للإيمان.', 'pro.heroBadgeActive': 'معاينة PRO مفعّلة', 'pro.heroTitle': 'وقفة قصيرة.\nمعنى أعمق.', 'pro.heroText': 'كل العبادات الأساسية مجانية. يضيف Pro العمق: تذكير السنن، الوضع الليلي، الأصوات، الودجات.',
  'pro.monthly': 'شهري', 'pro.monthlySub': 'مرن، أوقفه متى شئت', 'pro.yearly': 'سنوي', 'pro.yearlySub': 'الأوفر · شهران مجانًا', 'pro.best': 'الأفضل', 'pro.soonPrice': 'قريبًا', 'pro.previewOn': 'معاينة Pro مفعّلة ✓', 'pro.previewTry': 'جرّب معاينة Pro مجانًا', 'pro.get': 'ما ستحصل عليه', 'pro.compare': 'مجاني مقابل Pro', 'pro.feature': 'الميزة', 'pro.free': 'مجاني', 'pro.footer': 'لا رسوم في هذه النسخة. القرآن الكامل وترجمته مجانيان للجميع.', 'pro.paymentSoon': 'يُفتح اشتراك Pro بعد تفعيل الدفع. استمتع بالمعاينة المجانية الآن.',
  'pro.f.sunnah': 'تذكير صلوات السنّة', 'pro.f.sunnahText': 'التهجّد، الضحى، الوتر، الرواتب · النيّة بالعربية واللاتينية.', 'pro.f.sunnahBadge': 'اضبط التذكير',
  'pro.f.dark': 'الوضع الليلي', 'pro.f.darkText': 'أزرق عميق، مريح لقيام الليل.', 'pro.f.darkOn': 'مفعّل ✓', 'pro.f.darkTry': 'جرّبه الآن',
  'pro.f.sound': 'أصوات مميّزة', 'pro.f.verse': 'وقفة مع آية', 'pro.f.verseText': 'تعرض شاشة الوقفة آية اليوم.', 'pro.f.demo': 'عرض توضيحي',
  'pro.f.widget': 'ودجة شاشة القفل', 'pro.f.widgetText': 'آية اليوم والعدّ التنازلي للأذان.', 'pro.f.widgetBadge': 'شاهد التصميم',
  'pro.f.hajj': 'الحج والعمرة', 'pro.f.hajjText': 'دليل خطوة بخطوة: التحضير، العمرة، الحج، الأدعية.', 'pro.f.hajjBadge': 'افتح الدليل',
  'pro.f.rakaat': 'عدّاد الركعات', 'pro.f.rakaatText': 'بحث في المستشعرات · غير متاح بعد.', 'pro.f.concept': 'مفهوم',
  'pro.c.basic': 'المواقيت، القرآن، القبلة، السلسلة', 'pro.c.ambient': 'المطر والقطة (الصوت)', 'pro.c.sunnah': 'تذكير السنن + النيّات', 'pro.c.dark': 'الوضع الليلي وودجة شاشة القفل', 'pro.c.sound': 'أصوات مميّزة: رعد، أمواج، نار، طيور', 'pro.c.verse': 'وقفة الصلاة مع آية', 'pro.c.hajj': 'دليل الحج والعمرة', 'pro.c.ads': 'بدون إعلانات للأبد',
  'sunnah.title': 'صلوات السنّة', 'sunnah.subtitle': 'تذكير لطيف ونيّات جاهزة للقراءة.', 'sunnah.proNote': 'ميزة Pro · فعّل المعاينة المجانية لتشغيل التذكير.', 'sunnah.enablePro': 'تفعيل معاينة Pro', 'sunnah.reminder': 'تذكير', 'sunnah.niat': 'النيّة', 'sunnah.time': 'الوقت التقديري', 'sunnah.rakaat': 'ركعة', 'sunnah.on': 'تذكير {name} مفعّل.', 'sunnah.off': 'تذكير {name} متوقف.', 'sunnah.notifHint': 'يصل التذكير كإشعار على الهاتف بعد منح عزم إذن الإشعارات.', 'sunnah.needNotif': 'إذن الإشعارات غير مفعّل · اضبطه في الإعدادات → إشعارات الصلاة.', 'sunnah.footer': 'تُحسب الأوقات من جدول صلاة موقعك. اتبع معلّمك المحلي للأحكام التفصيلية.',
  'sunnah.tahajud': 'التهجّد', 'sunnah.tahajudDesc': 'صلاة الليل في الثلث الأخير بعد النوم. 2–12 ركعة، تُختم بالوتر.', 'sunnah.tahajudTime': 'الثلث الأخير من الليل',
  'sunnah.dhuha': 'الضحى', 'sunnah.dhuhaDesc': 'صلاة الصباح بعد ارتفاع الشمس إلى قبل الظهر. 2–12 ركعة.', 'sunnah.dhuhaTime': 'بعد الشروق',
  'sunnah.witir': 'الوتر', 'sunnah.witirDesc': 'ختام صلاة الليل بعدد فردي من الركعات (1، 3، 5…). بعد العشاء إلى قبل الفجر.', 'sunnah.witirTime': 'بعد العشاء',
  'sunnah.rawatib': 'الرواتب', 'sunnah.rawatibDesc': 'سنن الفرائض: 2 قبل الفجر، 2–4 قبل و2 بعد الظهر، 2 بعد المغرب، 2 بعد العشاء.', 'sunnah.rawatibTime': 'قبل الفرائض وبعدها',
  'sunnah.meaning.tahajud': 'نويت أن أصلي سنة التهجد ركعتين لله تعالى.', 'sunnah.meaning.dhuha': 'نويت أن أصلي سنة الضحى ركعتين لله تعالى.', 'sunnah.meaning.witir': 'نويت أن أصلي سنة الوتر ركعة لله تعالى.', 'sunnah.meaning.rawatib': 'نويت أن أصلي سنة الفجر ركعتين قبلية لله تعالى.',
  'focus.title': 'حاجب التطبيقات', 'focus.subtitle': 'الدنيا تنتظر. الصلاة أولًا.', 'focus.demo': 'عرض توضيحي داخل التطبيق', 'focus.blocking': 'حجب التطبيقات', 'focus.onSub': 'مفعّل · {n} دقيقة قبل الأذان', 'focus.offSub': 'متوقف · بدّل للتفعيل',
  'share.ownPhoto': 'صورتك', 'share.removePhoto': 'حذف الصورة', 'share.selfie': 'سيلفي', 'share.gallery': 'المعرض', 'share.center': 'في المنتصف', 'share.full': 'ملء الشاشة', 'share.template': 'خلفية القالب', 'share.tone': 'اللمسة', 'share.caption': 'التعليق', 'share.shuffle': 'عشوائي', 'share.stats': 'الإحصاءات', 'share.name': 'الاسم والمدينة', 'share.verse': 'الآية', 'share.buttonWeb': 'مشاركة كنص', 'share.button': 'مشاركة إلى Story / WhatsApp', 'share.photoHintWeb': 'السيلفي متاح على الهاتف؛ على الويب اختر من المعرض.', 'share.photoHint': 'يمكن لصورتك أن تملأ البطاقة كاملة أو تتوسّطها.',
  'modal.location': 'تحديد الموقع', 'modal.notifications': 'تذكير الصلاة', 'modal.alarm-form': 'منبّه جديد', 'modal.success': 'خطوة طيّبة', 'modal.share-verse': 'مشاركة الآية', 'modal.share-progress': 'مشاركة إلى Story', 'modal.share-badge': 'مشاركة الشارة', 'modal.day': 'سجل الصلاة', 'modal.ambient': 'جوّ هادئ', 'modal.adhan': 'وقت الصلاة', 'modal.add-app': 'إضافة تطبيق', 'modal.widget-preview': 'آية على شاشة القفل', 'modal.rakaat-preview': 'عدّاد الركعات', 'modal.logout': 'الخروج من عزم؟', 'modal.language': 'اللغة / Language', 'modal.profile': 'الملف الشخصي',
};

const STRINGS: Record<Lang, Record<Keys, string>> = { id, en, ms, ar };

/** Story captions: motivation + short ayat/hadith reminders. Per language so stories read naturally abroad. */
export const CAPTIONS: Record<Lang, string[]> = {
  id: ['Bukan sempurna, tetap berusaha', 'Jeda sejenak, dekat kembali', 'Alhamdulillah, satu hari lagi', 'Sibuk boleh, salat jangan tertunda', 'Lima waktu, satu tujuan', 'Tenang itu pilihan, salat itu jalannya', 'Hari ini aku menang dari malas', 'Pelan-pelan, yang penting terus', 'Dunia menunggu, Allah lebih dulu', 'Satu sujud lebih berarti dari seribu scroll', 'Konsisten kecil, dampak besar', 'Bismillah, lanjut lagi besok', 'Jaga salat, salat menjagamu', 'Sesungguhnya salat mencegah dari keji dan mungkar (QS 29:45)', 'Hanya dengan mengingat Allah hati menjadi tenang (QS 13:28)', 'Sungguh bersama kesulitan ada kemudahan (QS 94:6)', 'Mintalah pertolongan dengan sabar dan salat (QS 2:45)', 'Ingatlah Aku, niscaya Aku ingat kalian (QS 2:152)', 'Amal yang paling dicintai Allah: yang rutin walau sedikit (HR Bukhari)', 'Salat adalah cahaya (HR Muslim)', 'Antara kufur dan iman adalah meninggalkan salat (HR Muslim)', 'Sebaik-baik amal adalah salat pada waktunya (HR Bukhari)', 'Ya Allah, tolong aku untuk mengingat-Mu', 'Hari ini cukup: sujud, syukur, sabar', 'Layar bisa menunggu, azan tidak', 'Rezeki dijemput, salat dijaga', 'Tegakkan salat, tegakkan hidupmu', 'Bukan streak yang dikejar, ridha-Nya yang dicari', 'Sujud terakhirku, semoga bukan yang terakhir', 'Bersyukur hari ini masih dipanggil-Nya'],
  en: ['Not perfect, still trying', 'Pause a moment, return closer', 'Alhamdulillah, one more day', 'Busy is fine, prayer is never late', 'Five times, one purpose', 'Calm is a choice, prayer is the way', 'Today I beat laziness', 'Slowly, but never stopping', 'The world can wait, Allah comes first', 'One sujood means more than a thousand scrolls', 'Small consistency, big impact', 'Bismillah, again tomorrow', 'Guard your prayer, it guards you', 'Prayer restrains from shameful and evil deeds (Qur’an 29:45)', 'Only in the remembrance of Allah do hearts find rest (Qur’an 13:28)', 'Verily, with hardship comes ease (Qur’an 94:6)', 'Seek help through patience and prayer (Qur’an 2:45)', 'Remember Me, and I will remember you (Qur’an 2:152)', 'The deeds most loved by Allah are the steady ones (Bukhari)', 'Prayer is light (Muslim)', 'Between a man and disbelief is abandoning prayer (Muslim)', 'The best deed is prayer at its time (Bukhari)', 'O Allah, help me remember You', 'Today was enough: sujood, gratitude, patience', 'Screens can wait, the adhan cannot', 'Provision comes, prayer stays', 'Establish prayer, establish your life', 'Not chasing streaks, seeking His pleasure', 'May my last sujood not be my last', 'Grateful He still calls me today'],
  ms: ['Bukan sempurna, tetap berusaha', 'Jeda seketika, dekat kembali', 'Alhamdulillah, satu hari lagi', 'Sibuk boleh, solat jangan tertunda', 'Lima waktu, satu tujuan', 'Tenang itu pilihan, solat itu jalannya', 'Hari ini aku menang daripada malas', 'Perlahan, asalkan terus', 'Dunia menunggu, Allah lebih dahulu', 'Satu sujud lebih bererti daripada seribu skrol', 'Konsisten kecil, kesan besar', 'Bismillah, sambung lagi esok', 'Jaga solat, solat menjagamu', 'Sesungguhnya solat mencegah daripada keji dan mungkar (QS 29:45)', 'Hanya dengan mengingati Allah hati menjadi tenang (QS 13:28)', 'Sesungguhnya bersama kesukaran ada kemudahan (QS 94:6)', 'Mohonlah pertolongan dengan sabar dan solat (QS 2:45)', 'Ingatlah Aku, nescaya Aku ingat kamu (QS 2:152)', 'Amal paling dicintai Allah: yang berterusan walau sedikit (HR Bukhari)', 'Solat itu cahaya (HR Muslim)', 'Sebaik-baik amal ialah solat pada waktunya (HR Bukhari)', 'Ya Allah, bantu aku mengingati-Mu', 'Hari ini cukup: sujud, syukur, sabar', 'Skrin boleh menunggu, azan tidak', 'Rezeki dijemput, solat dijaga', 'Dirikan solat, dirikan hidupmu', 'Bukan streak yang dikejar, reda-Nya yang dicari', 'Bersyukur hari ini masih dipanggil-Nya'],
  ar: ['لستُ كاملًا، لكنّي أحاول', 'وقفة قصيرة، وعودة أقرب', 'الحمد لله، يومٌ آخر', 'الانشغال مقبول، تأخير الصلاة لا', 'خمس أوقات، غاية واحدة', 'السكينة اختيار، والصلاة طريقها', 'اليوم غلبتُ الكسل', 'ببطء، لكن بلا توقف', 'الدنيا تنتظر، والله أولًا', 'سجدة واحدة خير من ألف تمرير', 'ثبات صغير، أثر كبير', 'بسم الله، وغدًا نواصل', 'احفظ الصلاة تحفظك', 'إِنَّ الصَّلَاةَ تَنْهَى عَنِ الْفَحْشَاءِ وَالْمُنْكَرِ (العنكبوت 45)', 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ (الرعد 28)', 'إِنَّ مَعَ الْعُسْرِ يُسْرًا (الشرح 6)', 'وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ (البقرة 45)', 'فَاذْكُرُونِي أَذْكُرْكُمْ (البقرة 152)', 'أحبّ الأعمال إلى الله أدومها وإن قلّ (البخاري)', 'الصلاة نور (مسلم)', 'أفضل الأعمال الصلاة على وقتها (البخاري)', 'اللهم أعنّي على ذكرك', 'اليوم يكفي: سجود وشكر وصبر', 'الشاشة تنتظر، الأذان لا', 'الرزق يأتي، والصلاة تبقى', 'أقم الصلاة تُقم حياتك', 'لا أطلب السلسلة، بل رضاه', 'شكرًا لله أنه ما زال يدعوني'],
};

let active: Lang = 'id';
const listeners = new Set<() => void>();
export function setLanguage(lang: Lang | null | undefined) {
  active = LANGUAGES.some(l => l.key === lang) ? (lang as Lang) : 'id';
  listeners.forEach(fn => fn());
}
export function getLanguage() { return active; }
function subscribe(fn: () => void) { listeners.add(fn); return () => { listeners.delete(fn); }; }
export function translate(key: Keys, vars?: Record<string, string | number>, lang: Lang = active) {
  let text = STRINGS[lang][key] ?? STRINGS.id[key] ?? key;
  if (vars) Object.entries(vars).forEach(([k, v]) => { text = text.replace(`{${k}}`, String(v)); });
  return text;
}
/** Reactive translation hook: `const { t, lang, locale } = useI18n()`. */
export function useI18n() {
  const lang = useSyncExternalStore(subscribe, () => active, () => 'id' as Lang);
  return { lang, locale: LANGUAGES.find(l => l.key === lang)!.locale, t: (key: Keys, vars?: Record<string, string | number>) => translate(key, vars, lang), prayer: (name: string) => translate(`prayer.${name}` as Keys, undefined, lang) };
}
